[package]
name = "aztec_backend"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

acvm = { git = "https://github.com/noir-lang/noir" }
barretenberg_wrapper = { optional = true, git = "https://github.com/AztecProtocol/barretenberg", rev = "804c7dcf21111acd1302a768a8fa2f453dcec50f" }

sha2 = "0.9.3"
blake2 = "0.9.1"
sled = "0.34.6"

dirs = "3.0"
downloader = { version = "0.2.6", optional = true }

indicatif = "0.15.0"
regex = "1.4.0"

num-bigint = "0.4"
num-traits = "0.2.8"

hex = "*"

wasmer = { version = "*", default-features = false }


wasm-bindgen = { version = "*", optional = true }
js-sys = { version = "0.3.55", optional = true }
getrandom = { version = "0.2.4", features = ["js"], optional = true }

tempfile = "3.2.0"

[features]
default = ["wasm-base"]
wasm = [
    "acvm/bn254",
    "wasmer/js-default",
    "wasm-bindgen/serde-serialize",
    "js-sys",
    "getrandom",
] # This feature is enabled if we are using wasm
# and compiling the program to wasm32
# This feature is enabled if we are using wasm
# and compiling the program to a cpu target
wasm-base = ["acvm/bn254", "wasmer/sys-default"]
sys = [
    "downloader",
    "barretenberg_wrapper",
    "acvm/bn254",
    "wasmer/sys",
    "wasmer/cranelift",
    "wasmer/default-compiler",
    "wasmer/default-cranelift",
    "wasmer/default-universal",
]
