[package]
name = "aztec_backend"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

acvm = { git = "https://github.com/noir-lang/noir" }
barretenberg_wrapper = { git = "https://github.com/AztecProtocol/barretenberg", rev = "804c7dcf21111acd1302a768a8fa2f453dcec50f" }

grumpkin = { git = "https://github.com/noir-lang/grumpkin", features = ["std"] }
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }

sha2 = "0.9.3"
blake2 = "0.9.1"
sled = "0.34.6"

dirs = "3.0"
downloader = "0.2.6"

indicatif = "0.15.0"
regex = "1.4.0"
once_cell = "1.5.2"

num-bigint = "0.4"
num-traits = "0.2.8"

[dev-dependencies]
tempfile = "3.2.0"
hex = "*"

[features]
default = ["acvm/bn254"]
